// <auto-generated />
using System;
using Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240908203111_DadosInjetados")]
    partial class DadosInjetados
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Api.Models.TabelaPrecoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ValorHoraAdicional")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorHoraInicial")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("TabelaPrecos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataFim = new DateTime(2024, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataInicio = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValorHoraAdicional = 5.00m,
                            ValorHoraInicial = 10.00m
                        },
                        new
                        {
                            Id = 2,
                            DataFim = new DateTime(2023, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataInicio = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ValorHoraAdicional = 4.00m,
                            ValorHoraInicial = 8.00m
                        });
                });

            modelBuilder.Entity("Api.Models.VeiculoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataEntrada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataSaida")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan?>("Duracao")
                        .HasColumnType("time");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PrecoHora")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TempoCobrado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ValorTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Veiculos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataEntrada = new DateTime(2024, 9, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            DataSaida = new DateTime(2024, 9, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Duracao = new TimeSpan(0, 2, 0, 0, 0),
                            Placa = "ABC1234",
                            PrecoHora = 10.00m,
                            TempoCobrado = 2m,
                            ValorTotal = 20.00m
                        },
                        new
                        {
                            Id = 2,
                            DataEntrada = new DateTime(2024, 9, 2, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            Placa = "XYZ5678"
                        },
                        new
                        {
                            Id = 3,
                            DataEntrada = new DateTime(2024, 8, 31, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            DataSaida = new DateTime(2024, 8, 31, 9, 45, 0, 0, DateTimeKind.Unspecified),
                            Duracao = new TimeSpan(0, 0, 45, 0, 0),
                            Placa = "LMN9101",
                            PrecoHora = 10.00m,
                            TempoCobrado = 0.5m,
                            ValorTotal = 5.00m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
